apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ template "zookeeper.name" . }}
    chart: {{ template "zookeeper.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  clusterIP: {{ .Values.service.clusterIP }}
  ports:
    - port: 2181 
      targetPort: 2181 
      name: client
    - port: 2888
      targetPort: 2888 
      name: peer
    - port: 3888
      targetPort: 3888 
      name: leader-election
  selector:
    app: {{ template "zookeeper.name" . }}
    release: {{ .Release.Name }}
