apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.Namespace }}
  labels:
    app: {{ template "cassandra-worker.name" . }}
    chart: {{ template "cassandra-worker.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 7000
      targetPort: 7000
      name: peer
    - port: 9160
      targetPort: 9160
      name: rpc
    - port: 7199
      targetPort: 7199
      name: jmx
    - port: 9042
      targetPort: 9042
      name: cql
  selector:
    app: {{ template "cassandra-worker.name" . }}
    release: {{ .Release.Name }}
